% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Jun-2018 12:19:44
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

ans = saveVarsMat.ans; % <10x10000 double> ÔªËØÌ«¶à

clear saveVarsMat;
